// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWD8iEAlqykrdRmqNznqLS8wgwgHllhDU',
    appId: '1:569101739146:web:f44c8d50ab044bfab4f973',
    messagingSenderId: '569101739146',
    projectId: 'clubos-f2eee',
    authDomain: 'clubos-f2eee.firebaseapp.com',
    storageBucket: 'clubos-f2eee.firebasestorage.app',
    measurementId: 'G-8C6LEP7V31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_2RleOnPYgOhxivPQ0cMQ6VUh1SxJZ4',
    appId: '1:569101739146:android:8066cd48c8f90b09b4f973',
    messagingSenderId: '569101739146',
    projectId: 'clubos-f2eee',
    storageBucket: 'clubos-f2eee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhNxfs7-E8_iEiSW8m8tcrtMayb6iNQQ',
    appId: '1:569101739146:ios:5646aac5937d806db4f973',
    messagingSenderId: '569101739146',
    projectId: 'clubos-f2eee',
    storageBucket: 'clubos-f2eee.firebasestorage.app',
    iosBundleId: 'com.example.clubOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhNxfs7-E8_iEiSW8m8tcrtMayb6iNQQ',
    appId: '1:569101739146:ios:5646aac5937d806db4f973',
    messagingSenderId: '569101739146',
    projectId: 'clubos-f2eee',
    storageBucket: 'clubos-f2eee.firebasestorage.app',
    iosBundleId: 'com.example.clubOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWD8iEAlqykrdRmqNznqLS8wgwgHllhDU',
    appId: '1:569101739146:web:dea68cf9e9f26fbeb4f973',
    messagingSenderId: '569101739146',
    projectId: 'clubos-f2eee',
    authDomain: 'clubos-f2eee.firebaseapp.com',
    storageBucket: 'clubos-f2eee.firebasestorage.app',
    measurementId: 'G-R6JNCH9KC4',
  );
}
